version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_ROOT_USER: postgres
    volumes:
      - my_drive:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  my_drive:
    external: false
